# Generated by Django 4.2.7 on 2025-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('tourist_img', models.ImageField(upload_to='places/')),
                ('weather', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_district', models.CharField(max_length=100)),
                ('google_map_link', models.URLField()),
                ('description', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='TouristImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('Tourist_img', models.ImageField(upload_to='places/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Touristapp.touristdestination')),
            ],
        ),
    ]
