# Generated by Django 4.2.7 on 2025-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdestination',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='tourist_img',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
