# Generated by Django 4.2.7 on 2025-02-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Touristapp', '0002_customuser_confirm_password_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('Tourist_img', models.ImageField(upload_to='more_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Touristapp.touristdestination')),
            ],
        ),
        migrations.DeleteModel(
            name='TouristDestinationImage',
        ),
    ]
